### ISSUE TITLE
When trying to authorize new ads account I am getting invalid_client Unathorized

### ISSUE THREAD

**Issue by mm86133** [fblascogarma/google_ads_backend#2]
Looks like client id is matching the id/secret in Console & Env & .json file.

Unfortunately I am still getting below error. I have authorized Google Ads / Google Business API's.

`Internal Server Error: /api/get-accounts/
Traceback (most recent call last):
  File "/home/mike/.local/lib/python3.10/site-packages/django/core/handlers/exception.py", line 47, in inner
    response = get_response(request)
  File "/home/mike/.local/lib/python3.10/site-packages/django/core/handlers/base.py", line 181, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/home/mike/.local/lib/python3.10/site-packages/django/views/decorators/csrf.py", line 54, in wrapped_view
    return view_func(*args, **kwargs)
  File "/home/mike/.local/lib/python3.10/site-packages/django/views/generic/base.py", line 70, in view
    return self.dispatch(request, *args, **kwargs)
  File "/home/mike/.local/lib/python3.10/site-packages/rest_framework/views.py", line 509, in dispatch
    response = self.handle_exception(exc)
  File "/home/mike/.local/lib/python3.10/site-packages/rest_framework/views.py", line 469, in handle_exception
    self.raise_uncaught_exception(exc)
  File "/home/mike/.local/lib/python3.10/site-packages/rest_framework/views.py", line 480, in raise_uncaught_exception
    raise exc
  File "/home/mike/.local/lib/python3.10/site-packages/rest_framework/views.py", line 506, in dispatch
    response = handler(request, *args, **kwargs)
  File "/home/mike/.local/lib/python3.10/site-packages/rest_framework/decorators.py", line 50, in handler
    return func(*args, **kwargs)
  File "/home/mike/google-ads/google_ads_backend/api/views.py", line 182, in list_ads_accounts
    list_of_accounts = list_accounts(refresh_token)
  File "/home/mike/google-ads/google_ads_backend/api/list_accessible_accounts.py", line 42, in list_accounts
    client = GoogleAdsClient.load_from_dict(credentials)
  File "/home/mike/.local/lib/python3.10/site-packages/google/ads/googleads/client.py", line 270, in load_from_dict
    kwargs = cls._get_client_kwargs(config_data)
  File "/home/mike/.local/lib/python3.10/site-packages/google/ads/googleads/client.py", line 184, in _get_client_kwargs
    "credentials": oauth2.get_credentials(config_data),
  File "/home/mike/.local/lib/python3.10/site-packages/google/ads/googleads/oauth2.py", line 113, in get_credentials
    return get_installed_app_credentials(
  File "/home/mike/.local/lib/python3.10/site-packages/google/ads/googleads/oauth2.py", line 47, in initialize_credentials_wrapper
    credentials.refresh(Request())
  File "/home/mike/.local/lib/python3.10/site-packages/google/oauth2/credentials.py", line 319, in refresh
    ) = reauth.refresh_grant(
  File "/home/mike/.local/lib/python3.10/site-packages/google/oauth2/reauth.py", line 349, in refresh_grant
    _client._handle_error_response(response_data, retryable_error)
  File "/home/mike/.local/lib/python3.10/site-packages/google/oauth2/_client.py", line 69, in _handle_error_response
    raise exceptions.RefreshError(
google.auth.exceptions.RefreshError: ('invalid_client: Unauthorized', {'error': 'invalid_client', 'error_description': 'Unauthorized'})
[25/Oct/2022 10:16:01] "POST /api/get-accounts/ HTTP/1.1" 500 134656
`

**Comment by fblascogarma** [comment]
Hi @mm86133 ,

Thank you for reaching out.

The error you are getting is caused by the client_secret that you use when building the credentials to consume the API doesn't match with the client secret of the Google Cloud project. 

Please follow these steps:

1. Login to your Google Cloud project. If you have more than one project, make sure you are inside the correct project.
2. Navigate the left-side menu bar > APIs & Services > Credentials. See image below.
<img width="441" alt="Credentials in Google Cloud project" src="https://user-images.githubusercontent.com/62343770/197896192-5bf0183a-2676-4c48-99be-f898524c9677.png">
3. Download OAuth client. See image below.
<img width="1330" alt="Download OAuth client" src="https://user-images.githubusercontent.com/62343770/197896556-78733077-73a9-425d-aadc-70b6b6809826.png">
4. A modal opens showing your client id AND your client secret. See image below.
<img width="1334" alt="Your client secret" src="https://user-images.githubusercontent.com/62343770/197897295-5ee2256d-7bc1-4b9d-add6-13491254bc78.png">
5. Check that your client secret is the same as the value you have on your environment variable GOOGLE_CLIENT_SECRET. If it's the same, close the terminal and open a new terminal. Try again and see if you still get that error.

<>

**Please let me know if this solved your issue.**

## Other considerations
The client secret and client id are two different things. If the issue was with the client id, you would get this error:

> ('invalid_client: The OAuth client was not found.', {'error': 'invalid_client', 'error_description': 'The OAuth client was not found.'})


As you are not getting this error, we can be sure that client id is not causing your issue.


Also, it seems that you are using Python 3.1. Is that correct? If so, please upgrade to Python 3.7+. The app requires at least version 3.7 to work correctly.

**Comment by mm86133** [comment]
Thanks for reply.

I.ve used specifically python 3.9 (currently it is python 3.10 as a default) and getting the same error.

Double checked printenv for client id/secret & verified against the json and google console.

They all the same.

I also run a check on other code and looks like same credentials are working fine with Google Ads API (getting the data).

When looked into requests, it looked like refresh token wasn't the same after I've reconnected Google account.

Also normally in other code I always set manager account id in order to get the data (it is a test account as for live it doesn't work), should I set it too in here ?

**Comment by fblascogarma** [comment]
I don't believe it's an issue with the refresh token because the error message would be like this:

> ('invalid_grant: Token has been expired or revoked.', {'error': 'invalid_grant', 'error_description': 'Token has been expired or revoked.'})

However, it might be an issue if it's a test account. Can you try with a real account?

Let me know if testing with a real account solved the issue.

**Comment by fblascogarma** [comment]
Hi @mm86133 , were you able to solve this issue? Was this helpful?

**Comment by mm86133** [comment]
> Hi @mm86133 , were you able to solve this issue? Was this helpful?

Never, as I've wrote before tokens/credentials are valid and working with other app. I've stopped trying after checking the credentials. 



> I don't believe it's an issue with the refresh token because the error message would be like this:
> 
> > ('invalid_grant: Token has been expired or revoked.', {'error': 'invalid_grant', 'error_description': 'Token has been expired or revoked.'})
> 
> However, it might be an issue if it's a test account. Can you try with a real account?
> 
> Let me know if testing with a real account solved the issue.

It is against T&C to use approved credentials for production with un-authorized by Google app, so it is impossible to test it with your code. Same dev tokens are working fine with other app.

**Comment by fblascogarma** [comment]
Not sure if you already did this, but to use the Google Business API you need to get your project approved for that API. This is a **different approval process** that you went through when getting a developer token for the Google Ads API.

Check out [here](https://docs.google.com/document/d/10WyzDUNZTVHhenWgCopf3YyaRDsyoavc7aHuOAMJF6Y/edit#bookmark=kix.jxnfpwpt2mvb) for further instructions.

I'll close this issue as it seems you already are working on another app but feel free to comment or re-open in case you have new information to share.

It would be interesting to see if the other app uses the Google Business API.

Thanks, @mm86133 !
